- deploy/releases/daily/appsody-app-operator.yaml
- deploy/stack_constants.yaml
PR for https://github.com/appsody/appsody-operator/issues/35:
- Added an empty config map YAML to `deploy/stack_constants.yaml` and `deploy/releases/daily/appsody-app-operator.yaml`
> Add empty ConfigMap for constants

- build/Dockerfile
- deploy/olm-catalog/appsody-operator/0.1.0/appsody-operator.v0.1.0.clusterserviceversion.yaml
- deploy/olm-catalog/appsody-operator/0.1.0/appsody_v1alpha1_appsodyapplication_crd.yaml
- pkg/controller/appsodyapplication/appsodyapplication_controller.go
- Read config map files from deploy folder locally or inside the image
- Apply them to the cluster, if already they exist ignore the error
- Stop operator if it can't find/create maps
- Improve formatting by removing redundant else blocks
Resolves #49
> Install ConfigMaps from image if not already present

- pkg/controller/appsodyapplication/appsodyapplication_controller.go
- pkg/controller/appsodyapplication/appsodyapplication_controller_test.go
Updated the test to verify new functionality of the reconcile function and added two separate tests for the configmap conditions. Also refactored the majority of the original test to improve code reusability and readability. 
Made a small change to the reconcile function to remove a warning occurring on two separate else blocks.
> Update to reconcile test

- test/e2e/appsody_probe.go
- test/e2e/appsody_test.go
- test/util/util.go
- Updates the default appsody application to use node-express instead of microprofile.
- Drastically speeds up our e2e tests.
- Includes additional test that adjust probe values after deployment, watching that it adjusts accordingly.
> Changed e2e test to use node as default stack

- test/util/util.go
- Adds service type and expose fields so that it is not using the config map defaults.
- Removes the reliance for config map defaults.
> Fixed reliance on the stack defaults for basic testing application.

- test/e2e/appsody_storage.go
- test/e2e/appsody_test.go
- Verifies that persistence storage configurations will reach a ready state.
- Verifies that once created the above storage config can be removed and the operator will return to a ready state deployment.
> Added e2e persistence test alongside storage test.

- .travis.yml
- Makefile
- deploy/releases/0.1.0/readme.md
- deploy/releases/daily/readme.md
- deploy/stack_defaults.yaml
- pkg/utils/utils.go
- pkg/utils/utils_test.go
- Removed default values in the `appsody-operator-defaults` `ConfigMap`
- Fixed `nil` panic in `pkg/utils/utils.go` if `service.Type` is not defined in the CR nor defaults `ConfigMap`
- Fixed typos in `deploy/releases/*/readme.md`
- Added help text into Makefile to list all make targets as well as what each target does as follows:
```
⇒  make
build-image                    Build operator Docker image and tag with "${OPERATOR_IMAGE}:${OPERATOR_IMAGE_TAG}"
build                          Compile the operator
clean                          Clean binary artifacts
...
```
- Updated Makefile to run all unit tests rather than a subset
- Fixed a unit test failuire that was checking for `ksvc`'s container name
> Cleanup configmap

- Makefile
- deploy/releases/daily/appsody-app-operator.yaml
- pkg/controller/appsodyapplication/appsodyapplication_controller.go
- pkg/controller/appsodyapplication/appsodyapplication_controller_test.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
- Add support for watching multiple namespaces by watching on all namespaces and filtering the events (via predicates) to the desired namespaces.
- Added new Make targets for easy operator installation and uninstallation.
- Added unit tests
> Add support for watching multiple namespaces

- doc/user-guide.md
- pkg/utils/utils.go
- Allows the user to add and overwrite labels
- Excludes the app.kubernetes.io/name field
Fixes #84
> Allows the user to add new labels and overwrite the old ones 

- doc/user-guide.md
Remove conflicting information about watching multiple namespaces from the user guide.
Makes `user-guide.md` consistent regarding support for watching multiple namespaces.
> Update user-guide to be consistent

- pkg/controller/appsodyapplication/appsodyapplication_controller_test.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
Added port name in format '9080-tcp' to service, and use it as reference for Route and ServiceMonitor
> Add name to port in service

- doc/user-guide.md
- Removed parenthesis from subsection of the link to additional kAppNav information from user-guide.md
- The link worked in VS Code with or without the parenthesis around kappnav but in Github it only links to that section without.
> Fix dead link to additional kAppNav integration info in user-guide.md

- test/e2e/appsody_autoscaling.go
- Changes how the autoscaling tests check that the HPA are ready
- More robust way to check than the previous implementation
> E2E AutoScaling Test

- pkg/utils/utils_test.go
- Adds unit test coverage for the kAppNav label/annotation updating method in utils.go
- Addresses lack of testing for the kAppNav integration
- Will want to investigate e2e testing as well down the line
No
> Unit Test for UpdateAppDefinition

- CHANGELOG.md
- doc/user-guide.md
- pkg/apis/appsody/v1beta1/appsodyapplication_types.go
- Change the label corresponding to the Appsody Stack information from `app.appsody.dev/stack` to `stack.appsody.dev/id`
Fixes #165
> Change label for stack

- test/e2e/appsody_knative.go
- Method that checked whether or not knative was installed in the cluster that e2e tests were being run in was not functioning as expected.
- Updated it to correctly check for knative namespace and skip the knative test if not present.
- This allows for easier local testing through minishift or environment that does not have knative
No
> Update knative test to correctly identify when knative is not installed

- .travis.yml
- CHANGELOG.md
- Makefile
- doc/troubleshooting.md
- must-gather/Dockerfile
- must-gather/LICENSE
- must-gather/README.md
- must-gather/gather_appsodyoperator/gather
- must-gather/gather_appsodyoperator/gather_appsody
- must-gather/gather_appsodyoperator/gather_appsodyoperator
- must-gather/gather_appsodyoperator/gather_knative
- must-gather/gather_appsodyoperator/gather_pods
- `Appsody Operator must-gather` is a tool built on top of OpenShift must-gather that expands its capabilities to gather information about the Appsody Operator.
- Creates a local directory with a dump of relevant troubleshooting information
- Includes information about the pods that are not in the ready state, appsody operator pod(s), knative, appsody application, and the resources that are managed by the operator
Fixes #148
> Appsody Operator must-gather

- .travis.yml
- Removes the docker build/push stage from travis to avoid overwriting the manifest list that will now be pushed from GHE
> Remove operator push stage

- doc/user-guide.md
- Updates the CRD table entry for `envFrom` to more accurately reflect it's usage.
Fixes #200 
**Note**:
- Once the wording here is approved, I can reflect this change in the application runtime as well since there's an issue to have documentation here point to that repo instead.
> Update envFrom description in user-guide

- .travis.yml
* Remove vendor cache to prevent overwriting cloned vendor folder
* Combine e2e tests and unit tests into a parallel stage
> Remove vendor cache from build

- CHANGELOG.md
- pkg/apis/appsody/v1beta1/appsodyapplication_types.go
- pkg/controller/appsodyapplication/appsodyapplication_controller.go
- pkg/utils/utils.go
- Adds OpenShift specific annotations, including `connects-to` when defined, to **all** relevant resources as per tips section in the links provided in connected issue.
- Adds the labels documented and included in the generic operator [here](https://github.com/application-stacks/runtime-component-operator/blob/master/doc/user-guide.md#labels)
- Brings default annotations to the following, when the applicable information is set: `app.openshift.io/connects-to` (service binding) and `app.openshift.io/vcs-uri`(new) .
Other annotations do not seem intuitive to infer currently, unless I'm missing some labels set by the appsody CLI that we can utilize.
The operator should now set every label referenced in the issue's …
> Add OpenShift recommended labels & annotations

- pkg/controller/appsodyapplication/appsodyapplication_controller.go
- Change monitoring label from `app.appsody.dev/monitor` to `monitor.appsody.dev/enabled`
Fixes #170
> Change monitoring label

- CHANGELOG.md
- build/Dockerfile
- deploy/olm-catalog/appsody-operator-certified/appsody-operator.package.yaml
- deploy/olm-catalog/appsody-operator-certified/appsody-operator.v0.4.1.clusterserviceversion.yaml
- deploy/releases/0.4.0/readme.md
- deploy/releases/0.4.1/appsody-app-cluster-rbac.yaml
- deploy/releases/0.4.1/appsody-app-crd.yaml
- deploy/releases/0.4.1/appsody-app-operator.yaml
- deploy/releases/0.4.1/readme.md
- go.mod
- go.sum
- pkg/controller/appsodyapplication/appsodyapplication_controller.go
- vendor/github.com/application-stacks/runtime-component-operator/pkg/utils/reconciler.go
- vendor/github.com/application-stacks/runtime-component-operator/pkg/utils/utils.go
- vendor/modules.txt
- version/version.go
Fixes the following issues:
- Auto scaling does not work as expected. The changes made to `Deployment` by `HorizontalPodAutoscaler` are reversed. ([#252](https://github.com/appsody/appsody-operator/issues/252))
- Operator might crash on startup when optional CRDs API group (eg. serving.knative.dev/v1alpha1) is available, but actual CRD (Knative Service) is not present. ([#251](https://github.com/appsody/appsody-operator/issues/251))
- Release 0.4.1
Fixes #
> Fixes auto-scaling issue + optional CRDs check + release 0.4.1

- scripts/build-releases.sh
-  Checkout the master branch after building and pushing other release commits, as the build manifest make target doesn't exist in previous commits. This wasn't a problem in Runtime Operator as these scripts were present from first release onward.
> Fix issue with manifest build target

- CHANGELOG.md
- build/Dockerfile
- deploy/olm-catalog/appsody-operator-certified/appsody-operator.package.yaml
- deploy/olm-catalog/appsody-operator-certified/appsody-operator.v0.5.1.clusterserviceversion.yaml
- deploy/olm-catalog/appsody-operator-community/0.5.1/appsody-operator.v0.5.1.clusterserviceversion.yaml
- deploy/olm-catalog/appsody-operator-community/0.5.1/appsodyapplications.appsody.dev.crd.yaml
- deploy/olm-catalog/appsody-operator-community/appsody-operator.package.yaml
- deploy/releases/0.5.1/appsody-app-cluster-rbac.yaml
- deploy/releases/0.5.1/appsody-app-crd.yaml
- deploy/releases/0.5.1/appsody-app-operator.yaml
- deploy/releases/0.5.1/readme.md
- go.mod
- go.sum
- pkg/apis/appsody/v1beta1/appsodyapplication_types.go
- vendor/github.com/application-stacks/runtime-component-operator/pkg/apis/appstacks/v1beta1/runtimecomponent_types.go
- vendor/github.com/application-stacks/runtime-component-operator/pkg/utils/utils.go
- vendor/modules.txt
- version/version.go
-  Fixes a crash when creating a ingress without `route` field specified
> Update operator base to v0.5.1

- test/e2e/appsody_kappnav.go
- test/e2e/appsody_test.go
- test/util/util.go
- Ports over kappnav e2e test from [#117](https://github.com/application-stacks/runtime-component-operator/pull/117)
Fixes #168
> Add kAppNav e2e testing to appsody

- deploy/olm-catalog/appsody-operator-certified/appsody-operator.package.yaml
- deploy/olm-catalog/appsody-operator-certified/appsody-operator.v0.6.1.clusterserviceversion.yaml
Adding a certified (only) 0.6.1 release to enable air gap.  It just changes the controller reference to be in digest form instead of tag form.
> Airgap support
