appsody/appsody-operator

- deploy/releases/daily/appsody-app-dependencies.yaml
- deploy/releases/daily/appsody-app-operator.yaml
- deploy/releases/daily/readme.md
- pkg/controller/appsodyapplication/appsodyapplication_controller.go
- pkg/utils/utils.go
Todo:
- specify namespace as appropriate in kubectl commands for daily release 
- if possible, improve error reporting of maxReplicas parameter not being specified
> Add HPA support + daily release

- pkg/controller/appsodyapplication/appsodyapplication_controller_test.go
- pkg/utils/reconciler.go
Initial unit test for reconcile https://github.ibm.com/WASCloudPrivate/roadmap-cloudpaks/issues/640
> adding initial reconcile test

- deploy/crds/appsody_v1alpha1_appsodyapplication_cr.yaml
- deploy/crds/appsody_v1alpha1_appsodyapplication_crd.yaml
- pkg/apis/appsody/v1alpha1/appsodyapplication_types.go
> Print additional columns for AppsodyApplication status

- deploy/releases/daily/appsody-app-crd.yaml
- deploy/releases/daily/appsody-app-operator.yaml
- deploy/stack_defaults.yaml
- pkg/controller/appsodyapplication/appsodyapplication_controller.go
- pkg/utils/utils.go
- Improve reconcile loop (do no reconcile until CR is fully initialized)
- Fix issue with volumeMounts mounthPath missing after StatefulSet is updated after initial creation
- Improve CM formatting
- Update daily CRD with latest changes
> Improve renconcile loop and CRD/CM updates

- .gitignore
- demo/0_vote_appsodyapplication_cr.yaml
- demo/1_vote_appsodyapplication_cr.yaml
- demo/2_vote_appsodyapplication_cr.yaml
- demo/3_vote_appsodyapplication_cr.yaml
- demo/README.md
- readme.md
Adding the videos to a demo page
> Adding demo / videos page

- deploy/releases/daily/appsody-app-operator.yaml
- deploy/stack_defaults.yaml
- go.mod
- pkg/controller/appsodyapplication/appsodyapplication_controller.go
- vendor/k8s.io/client-go/discovery/fake/discovery.go
- vendor/k8s.io/client-go/testing/actions.go
- vendor/k8s.io/client-go/testing/fake.go
- vendor/k8s.io/client-go/testing/fixture.go
- vendor/modules.txt
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
PR for https://github.com/appsody/appsody-operator/issues/37:
- Added support for YAML in the defaults/constants ConfigMap
- Changed installation ConfigMap data to YAML
> Add support for YAML in the defaults/constants ConfigMap

- build/Dockerfile
- deploy/releases/0.1.0/appsody-app-crd.yaml
- deploy/releases/0.1.0/appsody-app-operator.yaml
- deploy/releases/0.1.0/readme.md
- deploy/releases/daily/appsody-app-operator.yaml
- deploy/releases/daily/readme.md
- deploy/role.yaml
- deploy/stack_constants.yaml
> Add label and license to image + create release

- deploy/releases/0.1.0/readme.md
- deploy/releases/daily/readme.md
- Separate namespace instructions from actual installation
> Update release readme

- doc/troubleshooting.md
- doc/user-guide.md
- readme.md
PR for https://github.com/appsody/appsody-operator/issues/40:
- Updated documentation
> [WIP] Documentation

- doc/user-guide.md
> Fix typo in user-guide.md

- .travis.yml
Each stage is separate so we have to build image for the push, merging into one stage
> Merge build and push stage

- doc/user-guide.md
PR for #40:
- Added documentation for basic usage, environment variables and `ServiceAccount`
> Add basic usage, env and SA documentation

- deploy/releases/0.1.0/readme.md
- deploy/releases/daily/readme.md
- doc/user-guide.md
- Adds information about watching multiple namespaces
- Fixes typos
> Update readme files for watching multiple namespaces support

- deploy/cluster_role.yaml
- deploy/releases/daily/appsody-app-cluster-rbac.yaml
- deploy/releases/daily/appsody-app-operator.yaml
- deploy/role.yaml
Adds permissions for manipulating ServiceMonitors
> Add service monitor role permissions

- CHANGELOG.md
- deploy/releases/0.2.0/appsody-app-cluster-rbac.yaml
- deploy/releases/0.2.0/appsody-app-crd.yaml
- deploy/releases/0.2.0/appsody-app-operator.yaml
- deploy/releases/0.2.0/readme.md
- doc/user-guide.md
- Documentation for kAppNav support
- fix readme spelling and grammar errors
Fixes #94
> Documentation for kAppNav support + fix readme

- deploy/olm-catalog/appsody-operator/0.2.0/appsody-operator.v0.2.0.clusterserviceversion.yaml
- deploy/olm-catalog/appsody-operator/0.2.0/appsody_v1beta1_appsodyapplication_crd.yaml
- deploy/olm-catalog/appsody-operator/appsody-operator.package.yaml
Add new version of CVS for 0.2.0 release
Updated CRD and multi namespace support
> Add new operator version for OLM

- CHANGELOG.md
- build/Dockerfile
- deploy/releases/0.2.0/readme.md
- doc/user-guide.md
- Updates version label in Dockerfile of the operator
- Updates readme and changelog
No
No
Fixes #
> Update operator image label, readme and changelog

- deploy/olm-catalog/appsody-operator-certified/0.2.0/appsody-operator.v0.2.0.clusterserviceversion.yaml
- deploy/olm-catalog/appsody-operator-community/0.2.0/appsody-operator.v0.2.0.clusterserviceversion.yaml
- Update Appsody Operator OLM description
- Added `replaces: ...` instruction to the CSV
No
N/A
> Update OLM related artifacts

- pkg/utils/utils_test.go
- Unit tests for service monitor creation
> Add unit testing for CustomizeServiceMonitor

- doc/user-guide.md
- Adds Knative autoscaling limitation
- Fixes formatting, typo
No
> Update user-guide to add Knative limitation

- pkg/apis/appsody/v1beta1/appsodyapplication_types.go
- pkg/common/types.go
- pkg/controller/appsodyapplication/appsodyapplication_controller.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
This PR introduces BaseApplication interface and other for re-usability of utilities code
> Implement AppsodyApplication as BaseApplication interface

- pkg/apis/appsody/v1beta1/appsodyapplication_types.go
- pkg/common/types.go
- pkg/controller/appsodyapplication/appsodyapplication_controller.go
- pkg/utils/reconciler.go
- pkg/utils/reconciler_test.go
- Adds interface types for BaseApplicationStatus and StatusCondition
No
> Add interfaces for status and conditions

- build/Dockerfile
- deploy/releases/0.2.1/appsody-app-cluster-rbac.yaml
- deploy/releases/0.2.1/appsody-app-crd.yaml
- deploy/releases/0.2.1/appsody-app-operator.yaml
- deploy/releases/0.2.1/readme.md
- Changes for release v0.2.1
No
Fixes #159
> Release v0.2.1

- deploy/olm-catalog/appsody-operator-certified/0.2.1/appsody-operator.v0.2.1.clusterserviceversion.yaml
- deploy/olm-catalog/appsody-operator-certified/0.2.1/appsodyapplications.appsody.dev.crd.yaml
- deploy/olm-catalog/appsody-operator-certified/appsody-operator.package.yaml
- deploy/olm-catalog/appsody-operator-community/0.2.1/appsody-operator.v0.2.1.clusterserviceversion.yaml
- deploy/olm-catalog/appsody-operator-community/0.2.1/appsodyapplications.appsody.dev.crd.yaml
- deploy/olm-catalog/appsody-operator-community/appsody-operator.package.yaml
- Update OLM catalog artifacts for v0.2.1 release
No
Fixes #159
> Update OLM catalog for release v0.2.1

- CHANGELOG.md
- doc/user-guide.md
- pkg/apis/appsody/v1beta1/appsodyapplication_types.go
- pkg/common/types.go
- pkg/controller/appsodyapplication/appsodyapplication_controller.go
- pkg/utils/utils.go
- Adds annotations to resources except for monitoring
- The kAppNav dashboard will be looking for annotations in the next Kabanaro release
Fixes #174
> Adding annotations to all resources

- build/Dockerfile
- deploy/olm-catalog/appsody-operator-certified/appsody-operator.package.yaml
- deploy/olm-catalog/appsody-operator-certified/appsody-operator.v0.2.2.clusterserviceversion.yaml
- deploy/olm-catalog/appsody-operator-community/0.2.2/appsody-operator.v0.2.2.clusterserviceversion.yaml
- deploy/olm-catalog/appsody-operator-community/0.2.2/appsodyapplications.appsody.dev.crd.yaml
- deploy/olm-catalog/appsody-operator-community/appsody-operator.package.yaml
- deploy/releases/0.2.2/appsody-app-cluster-rbac.yaml
- deploy/releases/0.2.2/appsody-app-crd.yaml
- deploy/releases/0.2.2/appsody-app-operator.yaml
- deploy/releases/0.2.2/readme.md
- doc/user-guide.md
> Release v0.2.2 + readme changes

- deploy/crds/appsody_v1beta1_appsodyapplication_crd.yaml
- pkg/apis/appsody/v1beta1/appsodyapplication_types.go
- pkg/apis/appsody/v1beta1/zz_generated.deepcopy.go
- pkg/apis/appsody/v1beta1/zz_generated.openapi.go
- pkg/common/types.go
- pkg/controller/appsodyapplication/appsodyapplication_controller.go
- pkg/utils/utils.go
-  Adds init containers to the AppsodyApplication
-  Makes sure the resources created by operator are reconciled when modified or deleted 
Fixes #
#161 
#184 
#138
> Add init containers, watch and reconcile created resources

- CHANGELOG.md
- doc/user-guide.md
- Adds user guide for service binding
- Adds service binding to changelog
> Adds documentation for service binding

- CHANGELOG.md
- doc/user-guide.md
- pkg/apis/appsody/v1beta1/appsodyapplication_types.go
- pkg/utils/utils.go
- Updates the doc with added features
- Fixes a typo in Initialize as well as deployment/stateful selector update logic
> Update doc for init containers

- CONTRIBUTING.md
- readme.md
- Adds contributing guidelines for users to follow 
- Adds the CLA assistant tool
Fixes #205
> Contributing and CLA

- Makefile
- must-gather/README.md
- Changes the Makefile to build the correct dockerfile for the must gather tool
> Pointing to the correct Dockerfile for the must-gather tool

- deploy/releases/daily/appsody-app-cluster-rbac.yaml
- deploy/releases/daily/appsody-app-crd.yaml
- deploy/releases/daily/appsody-app-operator.yaml
- doc/user-guide.md
- pkg/apis/appsody/v1beta1/appsodyapplication_types.go
- pkg/common/config.go
- pkg/common/types.go
- pkg/controller/appsodyapplication/appsodyapplication_controller.go
- pkg/utils/reconciler.go
- pkg/utils/utils.go
Add certificate manager integration guide
Add default duration of 1 year to certificates and renewal times
> Add operator configuration map and some other improvements

- doc/user-guide.md
Signed-off-by: Navid Shakibapour <navid.shakibapour@gmail.com>
- Fixes issues in `doc/user-guide.md`
**Does this PR introduce a user-facing change?** N/A
**Which issue(s) this PR fixes**: N/A
> Doc update

- pkg/apis/appsody/v1beta1/appsodyapplication_types.go
- pkg/controller/appsodyapplication/appsodyapplication_controller.go
Signed-off-by: Navid Shakibapour <navid.shakibapour@gmail.com>
- Removed consumes.namespace fallback logic
Fixes #
> Removed code to fallback consumes.namespace to current namespace

- deploy/olm-catalog/appsody-operator-certified/appsody-operator.v0.4.0.clusterserviceversion.yaml
- deploy/olm-catalog/appsody-operator-certified/appsodyapplications.appsody.dev.crd.yaml
- deploy/olm-catalog/appsody-operator-community/0.4.0/appsody-operator.v0.4.0.clusterserviceversion.yaml
- deploy/olm-catalog/appsody-operator-community/0.4.0/appsodyapplications.appsody.dev.crd.yaml
- update olm-catalog files for 0.4.0 release
> Update olm-catalog files for 0.4.0 release

- deploy/olm-catalog/appsody-operator-certified/appsody-operator.v0.4.0.clusterserviceversion.yaml
- deploy/olm-catalog/appsody-operator-community/0.4.0/appsody-operator.v0.4.0.clusterserviceversion.yaml
> Update apiGroup in CSV

- test/e2e/appsody_autoscaling.go
- test/e2e/appsody_basic.go
- test/e2e/appsody_servicemonitor.go
- test/e2e/appsody_storage.go
- test/util/util.go
- Update autoscaling test to account better for user scenarios 
- Port utility method from runtime tests that makes updating resources more reliable
> Improve autoscaling test

- deploy/olm-catalog/appsody-operator-certified/appsody-operator.v0.4.1.clusterserviceversion.yaml
Updating certification sample (must be using a certified image)
> Updating sample

- test/e2e/appsody_servicebinding.go
- test/e2e/appsody_test.go
- test/util/util.go
- Add servicebinding e2e tests
> Add servicebinding e2e tests

- doc/user-guide.md
- Add link to service ports section
Fixes #
> Add link to service ports section
